const CalendarActionTypes = {
    TOGGLE_HIDDEN: 'TOGGLE_HIDDEN',
    SELECT_DATE: 'SELECT_DATE',
    CHECK_SELECTED_DATE: 'CHECK_SELECTED_DATE',
    INCREASE_NAV: 'INCREASE_NAV',
    DECREASE_NAV: 'DECREASE_NAV',
    SET_DAYS: 'SET_DAYS',
    SET_DATE_DISPLAY: 'SET_DATE_DISPLAY',
    SET_CURRENT_DATE: 'SET_CURRENT_DATE',
}

export default CalendarActionTypes;
