const CalendarActionTypes = {
    SELECT_DATE: 'SELECT_DATE',
    TOGGLE_SHOW_TODO_MODAL: 'TOGGLE_SHOW_TODO_MODAL',
    INCREASE_NAV: 'INCREASE_NAV',
    DECREASE_NAV: 'DECREASE_NAV',
    SET_DAYS: 'SET_DAYS',
    SET_DATE_DISPLAY: 'SET_DATE_DISPLAY'
}

export default CalendarActionTypes;
