const TodosActionTypes = {
    COMPLETE_TODO: 'COMPLETE_TODO',
    CREATE_TODO: 'CREATE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    UPDATE_INCOMPLETE_TODOS: 'UPDATE_INCOMPLETE_TODOS',
    UPDATE_COMPLETED_TODOS: 'UPDATE_COMPLETED_TODOS',
};

export default TodosActionTypes;
