const ProgressActionTypes = {
    INCREMENT_PROGRESS_NAV: 'INCREMENT_PROGRESS_NAV',
    DECREMENT_PROGRESS_NAV: 'DECREMENT_PROGRESS_NAV',
    SET_PROGRESS_DATE_DISPLAY: 'SET_PROGRESS_DATE_DISPLAY',
}

export default ProgressActionTypes;
